name: Build Test

on:
  pull_request_target:
    types:
      - closed
    branches:
      - 'task/**'
# Test
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo The PR was merged
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Chmod permissions
        run: sudo chmod +x ./gradlew

      - name: Setup Gradle Cache
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-home-cache-cleanup: true
          cache-read-only: false

      # Run instrumentation tests here

      - name: API Wrapper Sample Assemble builds
        run: ./gradlew wrappers-sample:assembleRelease